/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

import lichsuTinh.lsTinhCoBan;

/**
 *
 * @author Yuu
 */
public class FormTinhCoBan extends javax.swing.JFrame {

    private double firstOperand = 0;
    private String currentOperation = "0";

    /**
     * Creates new form FormTinhCoBan
     */
    public FormTinhCoBan() {
        initComponents();
        txt_GiaTri.setText("0");
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_GiaTri = new java.awt.TextField();
        btn_9 = new javax.swing.JButton();
        btn_chia = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_tru = new javax.swing.JButton();
        btn_nhan = new javax.swing.JButton();
        btn_cong = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_xoaHet = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_bang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_ketQua = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_phay = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jButton13.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_GiaTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaTriActionPerformed(evt);
            }
        });

        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_chia.setText("/");
        btn_chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chiaActionPerformed(evt);
            }
        });

        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_tru.setText("-");
        btn_tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_truActionPerformed(evt);
            }
        });

        btn_nhan.setText("x");
        btn_nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhanActionPerformed(evt);
            }
        });

        btn_cong.setText("+");
        btn_cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_congActionPerformed(evt);
            }
        });

        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_xoaHet.setText("C");
        btn_xoaHet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaHetActionPerformed(evt);
            }
        });

        btn_xoa.setText("<-");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_bang.setText("=");
        btn_bang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bangActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Phép Tính Cơ Bản");

        txt_ketQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ketQuaActionPerformed(evt);
            }
        });

        jLabel2.setText("Giá trị");

        jLabel3.setText("Kết quả");

        btn_phay.setText(".");
        btn_phay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_xoaHet, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(btn_phay, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_bang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_chia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_nhan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tru, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cong, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_GiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ketQua, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_GiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ketQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_chia)
                    .addComponent(btn_nhan)
                    .addComponent(btn_tru)
                    .addComponent(btn_cong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_7)
                    .addComponent(btn_8)
                    .addComponent(btn_9)
                    .addComponent(btn_xoaHet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_4)
                    .addComponent(btn_5)
                    .addComponent(btn_6)
                    .addComponent(btn_xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1)
                    .addComponent(btn_2)
                    .addComponent(btn_3)
                    .addComponent(btn_0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_bang)
                    .addComponent(btn_phay))
                .addGap(25, 25, 25))
        );

        jMenu1.setText("Chức năng");

        jMenuItem1.setText("Quay lại menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Lịch sử tính");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_congActionPerformed
        if (txt_ketQua.getText().isEmpty()) {
            firstOperand = Double.parseDouble(txt_GiaTri.getText());
            txt_GiaTri.setText(txt_GiaTri.getText() + "+");
            currentOperation = "+"; // Lưu phép toán cộng
        } else {
            String formattedFirstOperand = String.format("%.2f", firstOperand);
            txt_GiaTri.setText(formattedFirstOperand);
            txt_GiaTri.setText(txt_GiaTri.getText() + "+");
            currentOperation = "+"; // Lưu phép toán cộng
        }
    }//GEN-LAST:event_btn_congActionPerformed

    private void btn_chiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chiaActionPerformed
        if (txt_ketQua.getText().isEmpty()) {
            firstOperand = Double.parseDouble(txt_GiaTri.getText());
            txt_GiaTri.setText(txt_GiaTri.getText() + " / ");
            currentOperation = "/"; // Lưu phép toán chia
        } else {
            String formattedFirstOperand = String.format("%.2f", firstOperand);
            txt_GiaTri.setText(formattedFirstOperand);
            txt_GiaTri.setText(txt_GiaTri.getText() + " / ");
            currentOperation = "/"; // Lưu phép toán chia
        }
    }//GEN-LAST:event_btn_chiaActionPerformed

    private void btn_xoaHetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaHetActionPerformed
        firstOperand = 0;
        currentOperation = "0";
        txt_GiaTri.setText("0");  // Đặt lại trường nhập thành chuỗi rỗng
        txt_ketQua.setText("");
    }//GEN-LAST:event_btn_xoaHetActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        String currentText = txt_GiaTri.getText();  // Lấy nội dung hiện tại
        if (currentText.length() > 0) {  // Nếu không phải là chuỗi rỗng
            txt_GiaTri.setText(currentText.substring(0, currentText.length() - 1));  // Cắt bỏ ký tự cuối
        }
        txt_ketQua.setText("");
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void txt_GiaTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaTriActionPerformed

    }//GEN-LAST:event_txt_GiaTriActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        if (txt_GiaTri.getText().equals("0")) {
            txt_GiaTri.setText("");
        }
        if (txt_ketQua.getText().isEmpty()) {
            txt_GiaTri.setText(txt_GiaTri.getText() + "1");
        } else {
            txt_ketQua.setText("");
            txt_GiaTri.setText(txt_GiaTri.getText() + "1");
        }
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        if (txt_GiaTri.getText().equals("0")) {
            txt_GiaTri.setText("");
        }
        if (txt_ketQua.getText().isEmpty()) {
            txt_GiaTri.setText(txt_GiaTri.getText() + "2");
        } else {
            txt_ketQua.setText("");
            txt_GiaTri.setText(txt_GiaTri.getText() + "2");
        }

    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        if (txt_GiaTri.getText().equals("0")) {
            txt_GiaTri.setText("");
        }
        if (txt_ketQua.getText().isEmpty()) {
            txt_GiaTri.setText(txt_GiaTri.getText() + "3");
        } else {
            txt_ketQua.setText("");
            txt_GiaTri.setText(txt_GiaTri.getText() + "3");
        }    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        if (txt_GiaTri.getText().equals("0")) {
            txt_GiaTri.setText("");
        }
        if (txt_ketQua.getText().isEmpty()) {
            txt_GiaTri.setText(txt_GiaTri.getText() + "4");
        } else {
            txt_ketQua.setText("");
            txt_GiaTri.setText(txt_GiaTri.getText() + "4");
        }    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        if (txt_GiaTri.getText().equals("0")) {
            txt_GiaTri.setText("");
        }
        if (txt_ketQua.getText().isEmpty()) {
            txt_GiaTri.setText(txt_GiaTri.getText() + "5");
        } else {
            txt_ketQua.setText("");
            txt_GiaTri.setText(txt_GiaTri.getText() + "5");
        }    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        if (txt_GiaTri.getText().equals("0")) {
            txt_GiaTri.setText("");
        }
        if (txt_ketQua.getText().isEmpty()) {
            txt_GiaTri.setText(txt_GiaTri.getText() + "6");
        } else {
            txt_ketQua.setText("");
            txt_GiaTri.setText(txt_GiaTri.getText() + "6");
        }    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        if (txt_GiaTri.getText().equals("0")) {
            txt_GiaTri.setText("");
        }
        if (txt_ketQua.getText().isEmpty()) {
            txt_GiaTri.setText(txt_GiaTri.getText() + "7");
        } else {
            txt_ketQua.setText("");
            txt_GiaTri.setText(txt_GiaTri.getText() + "7");
        }    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        if (txt_GiaTri.getText().equals("0")) {
            txt_GiaTri.setText("");
        }
        if (txt_ketQua.getText().isEmpty()) {
            txt_GiaTri.setText(txt_GiaTri.getText() + "8");
        } else {
            txt_ketQua.setText("");
            txt_GiaTri.setText(txt_GiaTri.getText() + "8");
        }    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        if (txt_GiaTri.getText().equals("0")) {
            txt_GiaTri.setText("");
        }
        if (txt_ketQua.getText().isEmpty()) {
            txt_GiaTri.setText(txt_GiaTri.getText() + "9");
        } else {
            txt_ketQua.setText("");
            txt_GiaTri.setText(txt_GiaTri.getText() + "9");
        }    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_nhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhanActionPerformed
        if (txt_ketQua.getText().isEmpty()) {
            firstOperand = Double.parseDouble(txt_GiaTri.getText());
            txt_GiaTri.setText(txt_GiaTri.getText() + " x ");
            currentOperation = "x"; // Lưu phép toán nhân
        } else {
            String formattedFirstOperand = String.format("%.2f", firstOperand);
            txt_GiaTri.setText(formattedFirstOperand);
            txt_GiaTri.setText(txt_GiaTri.getText() + " x ");
            currentOperation = "x"; // Lưu phép toán nhân
        }


    }//GEN-LAST:event_btn_nhanActionPerformed

    private void btn_truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_truActionPerformed
        if (txt_GiaTri.getText().endsWith("-")) {
            txt_GiaTri.setText(txt_GiaTri.getText() + "-");
        } else {
            if (txt_ketQua.getText().isEmpty()) {
                firstOperand = Double.parseDouble(txt_GiaTri.getText());
                txt_GiaTri.setText(txt_GiaTri.getText() + "-");
                currentOperation = "-"; // Lưu phép toán trừ
            } else {
                String formattedFirstOperand = String.format("%.2f", firstOperand);
                txt_GiaTri.setText(formattedFirstOperand);
                txt_GiaTri.setText(txt_GiaTri.getText() + "-");
                currentOperation = "-"; // Lưu phép toán trừ
            }
        }

//        String currentText = txt_GiaTri.getText();
        // Nếu đang ở chế độ nhập số âm cho toán hạng thứ hai (đã có "- " rồi và cuối chuỗi là "-")
        // tức là nếu chuỗi kết thúc bằng " - -" thì không gán lại nữa.
//        if (currentText.endsWith(" - -")) {
//            return;
//        }
        // Nếu chưa có phép toán nào (currentOperation = "0") thì thực hiện thao tác bình thường:
//        if (currentOperation.equals("0")) {
//            firstOperand = Double.parseDouble(currentText);
//            currentOperation = "-";
//            // Hiển thị phép toán với khoảng trắng để làm rõ ranh giới
//            txt_GiaTri.setText(currentText + " - ");
//        } else {
//            // Nếu đã có phép toán và chuỗi kết thúc bằng " - " (nghĩa là đang chờ nhập toán hạng thứ hai)
//            // thì nhấn nút trừ lần nữa sẽ hiểu là đang nhập số âm cho toán hạng thứ hai.
//            if (currentText.endsWith(" - ")) {
//                txt_GiaTri.setText(currentText + "-");
//            } else if (!txt_ketQua.getText().isEmpty()) {
//                String formattedFirstOperand = String.format("%.2f", firstOperand);
//                txt_GiaTri.setText(formattedFirstOperand);
//                txt_GiaTri.setText(txt_GiaTri.getText() + "-");
//                currentOperation = "-"; // Lưu phép toán trừ
//            }
//        }
    }//GEN-LAST:event_btn_truActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        if (txt_GiaTri.getText().equals("0")) {
            txt_GiaTri.setText("");
        }
        if (txt_ketQua.getText().isEmpty()) {
            txt_GiaTri.setText(txt_GiaTri.getText() + "0");
        } else {
            txt_ketQua.setText("");
            txt_GiaTri.setText(txt_GiaTri.getText() + "0");
        }
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_bangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bangActionPerformed
        String inputText = txt_GiaTri.getText();
        double secondOperand = Double.parseDouble(inputText.substring(inputText.indexOf(currentOperation) + 1).trim()); // Lấy phần sau dấu phép toán

        double result = 0;
        switch (currentOperation) {
            case "+":
                result = firstOperand + secondOperand;
                break;
            case "-":
                result = firstOperand - secondOperand;
                break;
            case "x":
                result = firstOperand * secondOperand;
                break;
            case "/":
                if (secondOperand == 0) {
                    txt_ketQua.setText("Khong the chia cho 0!!!");
                    return;
                } else {
                    result = firstOperand / secondOperand;
                }
                break;
        }
        String formattedResult = String.format("%.2f", result);
        txt_ketQua.setText(formattedResult);
        // Cập nhật firstOperand để thực hiện phép tính liên tiếp
        firstOperand = result;
        // Thiết lập lại currentOperation về trạng thái mặc định (ví dụ "0")
        currentOperation = "0";
//        String inputText = txt_GiaTri.getText().trim();

        // Chúng ta giả sử định dạng của inputText luôn có dạng: "<firstOperand> - <secondOperand>"
        // Tuy nhiên, nếu secondOperand bắt đầu bằng "-" (từ chuỗi " - -..."), ta cần chuyển đổi.
//        int opIndex = inputText.indexOf(" - ");
//        if(opIndex == -1) {
//            txt_ketQua.setText("Lỗi định dạng!");
//            return;
//        }
//
//        // Lấy toán hạng thứ hai (có thể có nhiều dấu "-" liên tiếp)
//        String secondStr = inputText.substring(opIndex + 3).trim();
//        double secondOperand = 0;
//        try {
//            // Nếu secondStr bắt đầu bằng "--", thay "--" bằng "" và sau đó nhân với -1 để chuyển thành dương
//            // (ví dụ: secondStr="--4" -> "4" và giá trị sẽ trở thành -(-4)=+4)
//            if (secondStr.startsWith("-")) {
//                // Nếu chuỗi có nhiều dấu '-' liên tiếp, ta đếm số dấu
//                int count = 0;
//                while (count < secondStr.length() && secondStr.charAt(count) == '-') {
//                    count++;
//                }
//                // Nếu số dấu là chẵn -> số dương, nếu lẻ -> số âm.
//                String numericPart = secondStr.substring(count).trim();
//                secondOperand = Double.parseDouble(numericPart);
//                if (count % 2 != 0) {
//                    secondOperand = -secondOperand;
//                }
//            } else {
//                secondOperand = Double.parseDouble(secondStr);
//            }
//        } catch (NumberFormatException e) {
//            txt_ketQua.setText("Lỗi đầu vào");
//            return;
//        }
//
//        double result = 0;
//        switch (currentOperation) {
//            case "+":
//                result = firstOperand + secondOperand;
//                break;
//            case "-":
//                result = firstOperand - secondOperand;
//                break;
//            case "x":
//                result = firstOperand * secondOperand;
//                break;
//            case "/":
//                if (secondOperand == 0) {
//                    txt_ketQua.setText("Không thể chia cho 0!!!");
//                    return;
//                } else {
//                    result = firstOperand / secondOperand;
//                }
//                break;
//            default:
//                txt_ketQua.setText("Phép toán không hợp lệ");
//                return;
//        }
//
//        String formattedResult = String.format("%.2f", result);
//        txt_ketQua.setText(formattedResult);
//        // Cập nhật firstOperand để thực hiện phép tính liên tiếp
//        firstOperand = result;
//        // Đặt lại currentOperation về trạng thái mặc định, ví dụ "0"
//        currentOperation = "0";
//        // Xuất kết quả vào ô nhập (chuyển thành chuỗi)
//        txt_GiaTri.setText(String.valueOf(result));
    }//GEN-LAST:event_btn_bangActionPerformed

    private void txt_ketQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ketQuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ketQuaActionPerformed

    private void btn_phayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phayActionPerformed
        txt_GiaTri.setText(txt_GiaTri.getText() + ".");
    }//GEN-LAST:event_btn_phayActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        lichsuTinh.lsTinhCoBan frm = new lsTinhCoBan();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormTinhCoBan().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_bang;
    private javax.swing.JButton btn_chia;
    private javax.swing.JButton btn_cong;
    private javax.swing.JButton btn_nhan;
    private javax.swing.JButton btn_phay;
    private javax.swing.JButton btn_tru;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton btn_xoaHet;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField txt_GiaTri;
    private java.awt.TextField txt_ketQua;
    // End of variables declaration//GEN-END:variables
}
